=== marioalajarin/HitoIndividual_Lenguaje_Marcas2T_Mario_Alajarin_Escobar/HitoIndividual_Lenguaje_Marcas2T_Mario_Alajarin_Escobar/dtdpedidos.dtd
<!ELEMENT pedidos (a単o_2021, a単o_2022)>
<!ELEMENT a単o_2021 (trimestre_1, trimestre_2, trimestre_3, trimestre_4)>
<!ELEMENT trimestre_1 (info_pedidos*)>
<!ELEMENT info_pedidos (nombre, apellidos, telefono, direccion, correo_electronico, fecha_inclusion, info_individual_pedido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo_electronico (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT info_individual_pedido (detalle_numero_pedido, fecha_compra, fecha_entrega, total_factura, info_productos)>
<!ELEMENT detalle_numero_pedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_factura (#PCDATA)>
<!ELEMENT info_productos (info_producto)>
<!ELEMENT info_producto (nombre_producto, referencia, precio, unidades)>
<!ELEMENT nombre_producto (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

<!ELEMENT trimestre_2 (info_pedidos*)>


<!ELEMENT trimestre_3 (info_pedidos*)>


<!ELEMENT trimestre_4 (info_pedidos*)>



<!ELEMENT a単o_2022 (trimestre_1, trimestre_2, trimestre_3, trimestre_4)>

=== marioalajarin/HitoIndividual_Lenguaje_Marcas2T_Mario_Alajarin_Escobar/HitoIndividual_Lenguaje_Marcas2T_Mario_Alajarin_Escobar/pedidos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedidos SYSTEM "dtdpedidos.dtd">

<pedidos>
    <año_2021>
        <trimestre_1>
            <info_pedidos>
                <nombre>Nombre </nombre>
                <apellidos>Apellido </apellidos>
                <telefono>Teléfono </telefono>
                <direccion>
                    <calle>Calle </calle>
                    <ciudad>Ciudad</ciudad>
                    <codigo_postal>CP</codigo_postal>
                    <provincia>Provincia/Estado</provincia>
                </direccion>
                <correo_electronico>Correo electrónico</correo_electronico>
                <fecha_inclusion>Fecha de registro</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>Número de pedido</detalle_numero_pedido>
                    <fecha_compra>Fecha de compra</fecha_compra>
                    <fecha_entrega>Fecha de entrega</fecha_entrega>
                    <total_factura>Total de la factura</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>Nombre del producto</nombre_producto>
                            <referencia>Código de referencia</referencia>
                            <precio>Precio del producto</precio>
                            <unidades>Unidades deseadas</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Emelita</nombre>
                <apellidos>Hampstead</apellidos>
                <telefono>582-552-7583</telefono>
                <direccion>
                    <calle>0786 Thompson Circles</calle>
                    <ciudad>Kenner</ciudad>
                    <codigo_postal>05193</codigo_postal>
                    <provincia>Alabama</provincia>
                </direccion>
                <correo_electronico>ehampstead0@bizjournals.com</correo_electronico>
                <fecha_inclusion>20/01/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>001</detalle_numero_pedido>
                    <fecha_compra>20/01/2021</fecha_compra>
                    <fecha_entrega>27/01/2021</fecha_entrega>
                    <total_factura>228,99€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>Realme 10 AMOLED FHD+ 8/128GB Negro Libre</nombre_producto>
                            <referencia>AA1</referencia>
                            <precio>228,99€</precio>
                            <unidades>1</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Axel</nombre>
                <apellidos>Anthill</apellidos>
                <telefono>179-952-4515</telefono>
                <direccion>
                    <calle>3469 Ethelyn Vista</calle>
                    <ciudad>Little Rock</ciudad>
                    <codigo_postal>79462</codigo_postal>
                    <provincia>South Dakota</provincia>
                </direccion>
                <correo_electronico>aanthill1@phpbb.com</correo_electronico>
                <fecha_inclusion>22/02/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>002</detalle_numero_pedido>
                    <fecha_compra>22/02/2021</fecha_compra>
                    <fecha_entrega>01/03/2021</fecha_entrega>
                    <total_factura>1022,89€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>PcCom Gold Élite Intel Core i5-11400F/16GB/500GBSSD/RTX3060</nombre_producto>
                            <referencia>AA2</referencia>
                            <precio>1022,89€</precio>
                            <unidades>1</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Cyndy</nombre>
                <apellidos>Wadge</apellidos>
                <telefono>786-728-3977</telefono>
                <direccion>
                    <calle>46955 Mosciski Mill</calle>
                    <ciudad>Bismarck</ciudad>
                    <codigo_postal>05863</codigo_postal>
                    <provincia>Kansas</provincia>
                </direccion>
                <correo_electronico>swadge2@un.org</correo_electronico>
                <fecha_inclusion>22/02/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>003</detalle_numero_pedido>
                    <fecha_compra>22/02/2021</fecha_compra>
                    <fecha_entrega>01/03/2021</fecha_entrega>
                    <total_factura>1919,6€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>MSI GeForce RTX 3060 Ti VENTUS 2X 8GD6X OC 8GB GDDR6X</nombre_producto>
                            <referencia>AA3</referencia>
                            <precio>479,90€</precio>
                            <unidades>4</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Farley</nombre>
                <apellidos>Colthard</apellidos>
                <telefono>925-323-3578</telefono>
                <direccion>
                    <calle>455 Lea Walks</calle>
                    <ciudad>San Diego</ciudad>
                    <codigo_postal>75303</codigo_postal>
                    <provincia>California</provincia>
                </direccion>
                <correo_electronico>ncolthard3@marriott.com</correo_electronico>
                <fecha_inclusion>25/02/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>004</detalle_numero_pedido>
                    <fecha_compra>25/02/2021</fecha_compra>
                    <fecha_entrega>04/03/2021</fecha_entrega>
                    <total_factura>399€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>Forgeon Spica Leather Silla Gaming Gris</nombre_producto>
                            <referencia>AA4</referencia>
                            <precio>399€</precio>
                            <unidades>1</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Brandais</nombre>
                <apellidos>Hutten</apellidos>
                <telefono>812-327-6139</telefono>
                <direccion>
                    <calle>046 Giuseppe Streets</calle>
                    <ciudad>Casper</ciudad>
                    <codigo_postal>41999</codigo_postal>
                    <provincia>West Virginia</provincia>
                </direccion>
                <correo_electronico>rhutten4@shareasale.com</correo_electronico>
                <fecha_inclusion>02/03/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>005</detalle_numero_pedido>
                    <fecha_compra>02/03/2021</fecha_compra>
                    <fecha_entrega>09/03/2021</fecha_entrega>
                    <total_factura>9,99€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>Owlotech Start Webcam 720p</nombre_producto>
                            <referencia>AA5</referencia>
                            <precio>9,99€</precio>
                            <unidades>1</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Wilma</nombre>
                <apellidos>Taig</apellidos>
                <telefono>899-611-0473</telefono>
                <direccion>
                    <calle>8559 Schumm Glen</calle>
                    <ciudad>Casper</ciudad>
                    <codigo_postal>96890</codigo_postal>
                    <provincia>Wyoming</provincia>
                </direccion>
                <correo_electronico>rtaig5@imdb.com</correo_electronico>
                <fecha_inclusion>01/03/2021</fecha_inclusion>
                <info_individual_pedido>
                    <detalle_numero_pedido>006</detalle_numero_pedido>
                    <fecha_compra>03/03/2021</fecha_compra>
                    <fecha_entrega>10/03/2021</fecha_entrega>
                    <total_factura>21,99€</total_factura>
                    <info_productos>
                        <info_producto>
                            <nombre_producto>Owlotech Altavoz Bluetooth Mini Negro</nombre_producto>
                            <referencia>AA6</referencia>
                            <precio>21,99€</precio>
                            <unidades>1</unidades>
                        </info_producto>
                    </info_productos>
                </info_individual_pedido>
            </info_pedidos>
            <info_pedidos>
                <nombre>Kirsti</nombre>
                <apellidos>Vaskov</apellidos>
